export const LP_SHOWCASE = [
  {
    id: 'beauty',
    label: '美容室・サロン',
    name: '結い庵',
    copy: '余白に、品のよさが宿る。',
    heading: '朝、鏡の前で\nうまくいく髪を。',
    description: '髪と暮らしに向き合う、予約制サロン。',
    photo: '/salon/hero-1200.jpg',
    preset: 'refined',
    image: '/lp/showcase-beauty-v1.webp',
    tone: '#e7e0d5',
  },
  {
    id: 'restaurant',
    label: '飲食店・カフェ',
    name: '喫茶 余白',
    copy: '訪れたくなる、空気まで。',
    heading: '一杯の余白を、\n日々のまんなかに。',
    description: '季節の味と、ゆっくり流れる時間を。',
    photo: '/company/concepts/retreat.webp',
    preset: 'warm',
    image: '/lp/showcase-restaurant-v1.webp',
    tone: '#e1e7dc',
  },
  {
    id: 'construction',
    label: '工務店・設計',
    name: '暮らし設計室',
    copy: '仕事への想いを、端正に。',
    heading: '暮らしを聞く。\nそこから、つくる。',
    description: '暮らしの話からはじめる、住まいづくり。',
    photo: '/company/concepts/architecture.webp',
    preset: 'calm',
    image: '/lp/showcase-construction-v1.webp',
    tone: '#e1e5e8',
  },
  {
    id: 'retail',
    label: 'お店・物販',
    name: '日々の道具',
    copy: 'ものの魅力が、まっすぐ届く。',
    heading: '暮らしに、\n好きな道具を。',
    description: '日々の道具を、大切に選ぶお店です。',
    photo: '/company/concepts/ceramics.webp',
    preset: 'refined',
    image: '/lp/showcase-retail-v1.webp',
    tone: '#eee0d5',
  },
] as const;
